import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from '@next/font/google';
import Appbar from "./components/Appbar";



const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Select desired font weights
  variable: '--font-poppins',          // Optional: Custom CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${poppins.variable} antialiased  `}
      >
        <Appbar />
        {children}
      </body>
    </html>
  );
}
